### ISSUE TITLE
Add DSLR pictures for metadata tests

### ISSUE THREAD

**Issue by fwsmit** [immich-app/test-assets#4]
I'm making this issue to inform if DSLR pictures are desired to test if the metadata is correctly extracted. I'm interested in this, because currently the timezone information is not correctly extracted for my camera (Sony A7 first gen). Since I can set a timezone in the camera settings, I believe this information is stored somewhere in the metadata and it should be able to be extracted.

In [discord](https://discord.com/channels/979116623879368755/1206309678578016277/1206525061167845376) the following was mentioned by user "etnoy" leading me to this repository:
> Since the topic of timezones is a literal minefield the best way to start working on this is to have a bunch of assets to test with that exhibit a problem in the current setup. In the best case, maybe you have some photos you could donate to the public domain so that we can add them to our test assets. I will scale them down as we're really only interested in the metadata. They will then be added to this repository: https://github.com/immich-app/test-assets after which you can start making assertions in the form of e2e tests

**Comment by bo0tzz** [comment]
cc @etnoy

**Comment by etnoy** [comment]
Yes, if you have specific cameras with odd metadata, please add samples here and write tests. Make sure you publish your assets in the public domain

**Comment by fwsmit** [comment]
I will write a fix for it in exiftools-vendored, where I'll also add tests with example images. Is it still necessary to add tests here?

Ref: https://github.com/photostructure/exiftool-vendored.js/issues/187

**Comment by etnoy** [comment]
Why not? I'd like to have a wide variety of test assets in here so we can ensure problematic cases are handled well

**Comment by fwsmit** [comment]
Specifically the timezone metadata that I'm interested in should be handled by exiftools-vendored afaik. But of course it could still be useful to check other things here. I can of course provide the images. Not sure if I would want to write tests for it

**Comment by fwsmit** [comment]
I've asked for some example pictures to be submitted in this issue. 

> I'm working on resolving the issues with timezone detection for DSLR pictures. At least on my Sony A7 first gen it's possible to infer the timezone from the exif metadata. To fix this issue for other camera's as well, I need some example pictures.
> 
> To submit example pictures, please follow the following steps:
> - Set your camera to a time of 10:00 AM and a timezone of GMT+0 (No daylight savings time). Take the first picture.
> - Set your camera to a time of 10:00 AM and a timezone of GMT+8 (No daylight savings time). Take the second picture
> 
> Upload both pictures to the following github issue: https://github.com/photostructure/exiftool-vendored.js/issues/187. Please document clearly which image is which timezone and which camera you used.

**Comment by etnoy** [comment]
Ideally I'd like a few samples from most major DSLR cameras. As a Nikon user I've uploaded some raw files from my cameras. Feel free to upload some a7 samples.

**Comment by fwsmit** [comment]
I did some digging and I found an online repository of many raw images of different camera models. This repository is available under the creative commons license and can be found on https://rawsamples.ch/. I would suggest using this.

**Comment by etnoy** [comment]
> I did some digging and I found an online repository of many raw images of different camera models. This repository is available under the creative commons license and can be found on https://rawsamples.ch/. I would suggest using this.

That is a great repository, however the reason for having our own repo is that we use it in automatic testing. It appears that rawsamples is in the public domain, so if we find odd quirks we don't handle correctly I suggest copying in those specific cases into our repo. We can't just take in everything since git doesn't like lots of raw photos, we need to be smart in what we include.
